version: "3.9"

services:
  php:
    build: .
    container_name: php-stuff
    expose:
      - 9000

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.webserver
    container_name: nginx-stuff
    ports:
      - "8080:80"
    links:
      - php
