FROM nginx:1.21-alpine AS base

WORKDIR /var/www/html/public/
LABEL maintainer="Sergio Villanueva <sergiovillanueva@protonmail.com>"



FROM node:16.14-alpine AS js-build

WORKDIR /app
COPY . .
RUN \
    npm install && \
    npm run build



FROM base

COPY --from=js-build /app/public/ .
COPY nginx/default.conf /etc/nginx/conf.d/default.conf
